In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt, seaborn as sns
%matplotlib inline

In [245]:
%store -r ODI_2019 

In [246]:
 ODI_2019 

Team 1       Team 2       Winner     Margin           Ground  \
0    New Zealand    Sri Lanka  New Zealand    45 runs  Mount Maunganui   
1    New Zealand    Sri Lanka  New Zealand    21 runs  Mount Maunganui   
2    New Zealand    Sri Lanka  New Zealand   115 runs           Nelson   
3      Australia        India    Australia    34 runs           Sydney   
4      Australia        India        India  6 wickets         Adelaide   
..           ...          ...          ...        ...              ...   
140  Afghanistan  West Indies  West Indies    47 runs          Lucknow   
141  Afghanistan  West Indies  West Indies  5 wickets          Lucknow   
147        India  West Indies  West Indies  8 wickets          Chennai   
148        India  West Indies        India   107 runs    Visakhapatnam   
149        India  West Indies        India  4 wickets          Cuttack   

       Match Date   Scorecard  
0     Jan 3, 2019  ODI # 4074  
1     Jan 5, 2019  ODI # 4075  
2     Jan 8, 2019  ODI # 4076  
3    Jan 12, 2019  ODI # 4077  
4    Jan 15, 2019  ODI # 4078  
..            ...         ...  
140   Nov 9, 2019  ODI # 4214  
141  Nov 11, 2019  ODI # 4215  
147  Dec 15, 2019  ODI # 4221  
148  Dec 18, 2019  ODI # 4222  
149  Dec 22, 2019  ODI # 4223  

[119 rows x 7 columns]

In [247]:
ODI_2019_filter =ODI_2019.drop(['Margin','Ground','Scorecard'],axis = 1)

In [248]:
ODI_2019_filter

Team 1       Team 2       Winner    Match Date
0    New Zealand    Sri Lanka  New Zealand   Jan 3, 2019
1    New Zealand    Sri Lanka  New Zealand   Jan 5, 2019
2    New Zealand    Sri Lanka  New Zealand   Jan 8, 2019
3      Australia        India    Australia  Jan 12, 2019
4      Australia        India        India  Jan 15, 2019
..           ...          ...          ...           ...
140  Afghanistan  West Indies  West Indies   Nov 9, 2019
141  Afghanistan  West Indies  West Indies  Nov 11, 2019
147        India  West Indies  West Indies  Dec 15, 2019
148        India  West Indies        India  Dec 18, 2019
149        India  West Indies        India  Dec 22, 2019

[119 rows x 4 columns]

In [249]:
ODI_2019_filter = ODI_2019_filter.reset_index(drop=True)
ODI_2019_filter.loc[ODI_2019_filter.Winner == ODI_2019_filter['Team 1'],'Result']=1
ODI_2019_filter.loc[ODI_2019_filter.Winner == ODI_2019_filter['Team 2'], 'Result']=0
ODI_2019_filter.drop(['Winner'],axis=1, inplace=True)

ODI_2019_filter.head()

Team 1     Team 2    Match Date  Result
0  New Zealand  Sri Lanka   Jan 3, 2019     1.0
1  New Zealand  Sri Lanka   Jan 5, 2019     1.0
2  New Zealand  Sri Lanka   Jan 8, 2019     1.0
3    Australia      India  Jan 12, 2019     1.0
4    Australia      India  Jan 15, 2019     0.0

In [250]:
ODI_2019_filter['Result'] = ODI_2019_filter['Result'].fillna(0).astype(int)

In [251]:
ODI_2019_filter

Team 1       Team 2    Match Date  Result
0    New Zealand    Sri Lanka   Jan 3, 2019       1
1    New Zealand    Sri Lanka   Jan 5, 2019       1
2    New Zealand    Sri Lanka   Jan 8, 2019       1
3      Australia        India  Jan 12, 2019       1
4      Australia        India  Jan 15, 2019       0
..           ...          ...           ...     ...
114  Afghanistan  West Indies   Nov 9, 2019       0
115  Afghanistan  West Indies  Nov 11, 2019       0
116        India  West Indies  Dec 15, 2019       0
117        India  West Indies  Dec 18, 2019       1
118        India  West Indies  Dec 22, 2019       1

[119 rows x 4 columns]

In [252]:
ODI_2019_filter['Match Date'] = pd.to_datetime(ODI_2019_filter['Match Date']).dt.year

In [253]:
ODI_2019_filter

Team 1       Team 2  Match Date  Result
0    New Zealand    Sri Lanka        2019       1
1    New Zealand    Sri Lanka        2019       1
2    New Zealand    Sri Lanka        2019       1
3      Australia        India        2019       1
4      Australia        India        2019       0
..           ...          ...         ...     ...
114  Afghanistan  West Indies        2019       0
115  Afghanistan  West Indies        2019       0
116        India  West Indies        2019       0
117        India  West Indies        2019       1
118        India  West Indies        2019       1

[119 rows x 4 columns]

In [254]:
%store -r SL_Ave_2018
%store -r India_Ave_2018
%store -r pakistan_Ave_2018
%store -r Bankaladesh_Ave_2018
%store -r Newzeleand_Ave_2018
%store -r England_Ave_2018
%store -r WestIndies_Ave_2018
%store -r SouthAfrica_Ave_2018
%store -r Ireland_Ave_2018
%store -r Scotland_Ave_2018
%store -r Australia_Ave_2018
%store -r Afhanistan_Ave_2018

In [255]:
{'England':England_Ave_2018, 'South Africa':SouthAfrica_Ave_2018, 'Scotland':Scotland_Ave_2018, 'West Indies':WestIndies_Ave_2018, 
            'Pakistan':pakistan_Ave_2018, 'New Zealand': Newzeleand_Ave_2018, 'Sri Lanka':SL_Ave_2018, 'Afghanistan':Afhanistan_Ave_2018, 
            'Australia':Australia_Ave_2018, 'Bangladesh':Bankaladesh_Ave_2018, 'India':India_Ave_2018,'Ireland':Ireland_Ave_2018}

{'England': array([2.11471052e-17, 7.40148683e-17]),
 'South Africa': array([-3.41607085e-17, -1.15292391e-16]),
 'Scotland': array([-2.61228947e-17,  1.63268092e-16]),
 'West Indies': array([ 1.24344979e-16, -4.44089210e-18]),
 'Pakistan': array([1.00929366e-16, 1.27423324e-16]),
 'New Zealand': array([-1.59186390e-16, -1.17553026e-16]),
 'Sri Lanka': array([4.91060184e-17, 7.68615940e-17]),
 'Afghanistan': array([1.81141651e-16, 8.18059071e-17]),
 'Australia': array([ 8.8817842e-18, -8.8817842e-17]),
 'Bangladesh': array([-1.77635684e-17, -5.32907052e-17]),
 'India': array([1.0658141e-16, 0.0000000e+00]),
 'Ireland': array([-4.07081776e-17,  1.48029737e-16])}

In [256]:
dict_map= {'England':England_Ave_2018, 'South Africa':SouthAfrica_Ave_2018, 'Scotland':Scotland_Ave_2018, 'West Indies':WestIndies_Ave_2018, 
            'Pakistan':pakistan_Ave_2018, 'New Zealand': Newzeleand_Ave_2018, 'Sri Lanka':SL_Ave_2018, 'Afghanistan':Afhanistan_Ave_2018, 
            'Australia':Australia_Ave_2018, 'Bangladesh':Bankaladesh_Ave_2018, 'India':India_Ave_2018,'Ireland':Ireland_Ave_2018}

In [257]:
ODI_2019_filter['Team 1']=ODI_2019_filter['Team 1'].map(dict_map)

In [258]:
ODI_2019_filter['Team 2']=ODI_2019_filter['Team 2'].map(dict_map)

In [259]:
ODI_2019_filter

Team 1  \
0    [-1.5918638956022465e-16, -1.1755302613678128e...   
1    [-1.5918638956022465e-16, -1.1755302613678128e...   
2    [-1.5918638956022465e-16, -1.1755302613678128e...   
3      [8.881784197001253e-18, -8.881784197001253e-17]   
4      [8.881784197001253e-18, -8.881784197001253e-17]   
..                                                 ...   
114    [1.8114165138620975e-16, 8.180590707764311e-17]   
115    [1.8114165138620975e-16, 8.180590707764311e-17]   
116                      [1.0658141036401502e-16, 0.0]   
117                      [1.0658141036401502e-16, 0.0]   
118                      [1.0658141036401502e-16, 0.0]   

                                               Team 2  Match Date  Result  
0      [4.910601839688192e-17, 7.686159401251084e-17]        2019       1  
1      [4.910601839688192e-17, 7.686159401251084e-17]        2019       1  
2      [4.910601839688192e-17, 7.686159401251084e-17]        2019       1  
3                       [1.0658141036401502e-16, 0.0]        2019       1  
4                       [1.0658141036401502e-16, 0.0]        2019       0  
..                                                ...         ...     ...  
114  [1.2434497875801754e-16, -4.440892098500626e-18]        2019       0  
115  [1.2434497875801754e-16, -4.440892098500626e-18]        2019       0  
116  [1.2434497875801754e-16, -4.440892098500626e-18]        2019       0  
117  [1.2434497875801754e-16, -4.440892098500626e-18]        2019       1  
118  [1.2434497875801754e-16, -4.440892098500626e-18]        2019       1  

[119 rows x 4 columns]

In [260]:
ODI_2019_filter['Team 1'].dtypes

dtype('O')

In [261]:
Data_type =object
np_array = np.array(ODI_2019_filter['Team 1'], dtype=Data_type)

In [262]:
np_array

array([array([-1.59186390e-16, -1.17553026e-16]),
       array([-1.59186390e-16, -1.17553026e-16]),
       array([-1.59186390e-16, -1.17553026e-16]),
       array([ 8.8817842e-18, -8.8817842e-17]),
       array([ 8.8817842e-18, -8.8817842e-17]),
       array([ 8.8817842e-18, -8.8817842e-17]),
       array([-3.41607085e-17, -1.15292391e-16]),
       array([-3.41607085e-17, -1.15292391e-16]),
       array([-1.59186390e-16, -1.17553026e-16]),
       array([-3.41607085e-17, -1.15292391e-16]),
       array([-1.59186390e-16, -1.17553026e-16]),
       array([-3.41607085e-17, -1.15292391e-16]),
       array([-1.59186390e-16, -1.17553026e-16]),
       array([-3.41607085e-17, -1.15292391e-16]),
       array([-1.59186390e-16, -1.17553026e-16]),
       array([-1.59186390e-16, -1.17553026e-16]),
       array([-1.59186390e-16, -1.17553026e-16]),
       array([-1.59186390e-16, -1.17553026e-16]),
       array([-1.59186390e-16, -1.17553026e-16]),
       array([ 1.24344979e-16, -4.44089210e-18]),
      

In [263]:
ODI_2019_filter['Team 1'].values

array([array([-1.59186390e-16, -1.17553026e-16]),
       array([-1.59186390e-16, -1.17553026e-16]),
       array([-1.59186390e-16, -1.17553026e-16]),
       array([ 8.8817842e-18, -8.8817842e-17]),
       array([ 8.8817842e-18, -8.8817842e-17]),
       array([ 8.8817842e-18, -8.8817842e-17]),
       array([-3.41607085e-17, -1.15292391e-16]),
       array([-3.41607085e-17, -1.15292391e-16]),
       array([-1.59186390e-16, -1.17553026e-16]),
       array([-3.41607085e-17, -1.15292391e-16]),
       array([-1.59186390e-16, -1.17553026e-16]),
       array([-3.41607085e-17, -1.15292391e-16]),
       array([-1.59186390e-16, -1.17553026e-16]),
       array([-3.41607085e-17, -1.15292391e-16]),
       array([-1.59186390e-16, -1.17553026e-16]),
       array([-1.59186390e-16, -1.17553026e-16]),
       array([-1.59186390e-16, -1.17553026e-16]),
       array([-1.59186390e-16, -1.17553026e-16]),
       array([-1.59186390e-16, -1.17553026e-16]),
       array([ 1.24344979e-16, -4.44089210e-18]),
      

In [264]:
from sklearn.model_selection import train_test_split

In [265]:
from sklearn.metrics import classification_report

In [266]:
from sklearn.metrics import confusion_matrix

In [267]:
X =ODI_2019_filter.drop(['Result','Match Date'],axis=1)

In [268]:
y=ODI_2019_filter['Result']

In [269]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=42)

In [270]:
X_train.shape, X_test.shape

((83, 2), (36, 2))

In [271]:
pip install -U scikit-learn==0.21.3

Note: you may need to restart the kernel to use updated packages.


'K:\4th' is not recognized as an internal or external command,
operable program or batch file.


In [272]:
from sklearn.ensemble import RandomForestClassifier

In [273]:
classifier_rf = RandomForestClassifier(random_state=42, n_jobs=-1, max_depth=5,
                                       n_estimators=100, oob_score=True)

In [274]:
classifier_rf.fit(X_train, y_train)

ValueError: setting an array element with a sequence.

In [275]:
classifier_rf.oob_score_

AttributeError: 'RandomForestClassifier' object has no attribute 'oob_score_'

In [276]:
classifier_pred =classifier_rf.predict(X_test)

NotFittedError: This RandomForestClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [277]:
print(confusion_matrix(y_test,classifier_pred))
print('\n')
print(classification_report(y_test,classifier_pred))

[[ 9  9]
 [ 3 15]]


              precision    recall  f1-score   support

           0       0.75      0.50      0.60        18
           1       0.62      0.83      0.71        18

    accuracy                           0.67        36
   macro avg       0.69      0.67      0.66        36
weighted avg       0.69      0.67      0.66        36



In [278]:
 from sklearn.svm import SVC

In [279]:
model =svm.SVC()

In [280]:
model.fit(X_train,y_train)

ValueError: setting an array element with a sequence.

In [281]:
predictions=model.predict(X_test)

NotFittedError: This SVC instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [282]:
predictions

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1])

In [283]:
print(confusion_matrix(y_test,classifier_pred))
print('\n')
print(classification_report(y_test,classifier_pred))

[[ 9  9]
 [ 3 15]]


              precision    recall  f1-score   support

           0       0.75      0.50      0.60        18
           1       0.62      0.83      0.71        18

    accuracy                           0.67        36
   macro avg       0.69      0.67      0.66        36
weighted avg       0.69      0.67      0.66        36

